services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    env_file:
    - postgres.env
    - postgres.secret.env
  redis:
    image: redis
    ports:
      - 6379:6379
  cassandra:
    image: cassandra
    ports:
      - 9042:9042
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
  traefik:
    image: traefik:v3.6
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:8080
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  app:
    depends_on:
      - redis
      - postgres
      - cassandra
    build: ../
    env_file:
      - postgres.secret.env
      - app.env
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chattskiy.rule=PathPrefix(`/`)"
      - "traefik.http.services.chattskiy.loadbalancer.server.port=8080"
      - "prometheus-job=app"
